//! Polyomino shape generation, rotation, and reflection.

use crate::types::Shape;

/// All 8 symmetries of a free polyomino (rotation × reflection).
pub fn transforms(shape: &Shape) -> Vec<Vec<[isize; 2]>> {
    let mut seen = std::collections::HashSet::new();
    let mut result = Vec::new();

    let signed: Vec<[isize; 2]> = shape
        .iter()
        .map(|&[r, c]| [r as isize, c as isize])
        .collect();

    for &rotate in &[0, 1, 2, 3] {
        for &reflect in &[false, true] {
            let mut t: Vec<[isize; 2]> = signed
                .iter()
                .map(|&[r, c]| {
                    let (mut rr, mut cc) = (r, c);
                    if reflect {
                        cc = -cc;
                    }
                    for _ in 0..rotate {
                        (rr, cc) = (-cc, rr);
                    }
                    [rr, cc]
                })
                .collect();
            // Normalize
            let min_r = t.iter().map(|xy| xy[0]).min().unwrap_or(0);
            let min_c = t.iter().map(|xy| xy[1]).min().unwrap_or(0);
            for xy in &mut t {
                xy[0] -= min_r;
                xy[1] -= min_c;
            }
            t.sort();
            if seen.insert(t.clone()) {
                result.push(t);
            }
        }
    }
    result
}

/// All free polyominoes (one representative per rotation/reflection class) of
/// exactly `area` cells.  Generated by BFS over size: start from the monomino,
/// repeatedly attach a neighbour cell, keep only the canonical (dihedral-min)
/// form of each new shape.  Used by the homogeneous (gemini) exact-cover path
/// in `pieces.rs`.  Sizes up to ~10 are cheap; callers should cap larger areas.
#[allow(dead_code)] // gemini exact-cover path currently bypasses this generator
pub fn enumerate_free_polyominoes(area: usize) -> Vec<Shape> {
    if area == 0 {
        return Vec::new();
    }
    let mut current: Vec<Vec<[i32; 2]>> = vec![vec![[0i32, 0i32]]];
    for _ in 1..area {
        let mut seen = std::collections::HashSet::new();
        let mut next = Vec::new();
        for poly in &current {
            for &[r, c] in poly {
                for [dr, dc] in [[1i32, 0i32], [-1, 0], [0, 1], [0, -1]] {
                    let nr = r + dr;
                    let nc = c + dc;
                    if poly.iter().any(|&[pr, pc]| pr == nr && pc == nc) {
                        continue;
                    }
                    let mut np = poly.clone();
                    np.push([nr, nc]);
                    let canon = canonicalize(&np);
                    if seen.insert(canon.clone()) {
                        next.push(canon);
                    }
                }
            }
        }
        if next.is_empty() {
            break;
        }
        current = next;
    }
    // Dedupe defensively and convert to `Shape` (non-negative after canonicalize).
    let mut seen = std::collections::HashSet::new();
    let mut out = Vec::new();
    for poly in current {
        let canon = canonicalize(&poly);
        if seen.insert(canon.clone()) {
            out.push(canon.into_iter().map(|[r, c]| [r as usize, c as usize]).collect());
        }
    }
    out
}

/// Canonical form of a polyomino: the lexicographically smallest of its 8
/// dihedral transforms, normalized so the minimum coordinate is the origin.
fn canonicalize(poly: &[[i32; 2]]) -> Vec<[i32; 2]> {
    let mut best: Option<Vec<[i32; 2]>> = None;
    for &rotate in &[0u8, 1, 2, 3] {
        for &reflect in &[false, true] {
            let mut t: Vec<[i32; 2]> = poly
                .iter()
                .map(|&[r, c]| {
                    let (mut rr, mut cc) = (r, c);
                    if reflect {
                        cc = -cc;
                    }
                    for _ in 0..rotate {
                        let (nrr, ncc) = (-cc, rr);
                        rr = nrr;
                        cc = ncc;
                    }
                    [rr, cc]
                })
                .collect();
            let min_r = t.iter().map(|xy| xy[0]).min().unwrap_or(0);
            let min_c = t.iter().map(|xy| xy[1]).min().unwrap_or(0);
            for xy in &mut t {
                xy[0] -= min_r;
                xy[1] -= min_c;
            }
            t.sort();
            if best.as_ref().map_or(true, |b| &t < b) {
                best = Some(t);
            }
        }
    }
    best.unwrap()
}
